mixed-port: 7890
allow-lan: false
mode: Rule
log-level: info

proxies:
  - name: VLESS ยง 0
    type: vless
    server: 66.151.42.167
    port: 443
    uuid: b91853a0-4ca7-4d93-8221-b1c6c169862f
    udp: true
    flow: xtls-rprx-vision
    tls: true
    servername: www.cloudflare.com           # SNI
    client-fingerprint: chrome               # utls: chrome
    reality-opts:
      public-key: 4xk8Lo0BdQcMEzunr8N0ozVqWxv0ENq5cJyM6EvRqng
      short-id: abcd1234
    packet-encoding: xudp

proxy-groups:
  - name: Proxy
    type: select
    proxies:
      - VLESS ยง 0
      - DIRECT

rules:
  - MATCH,Proxy

